name: eup
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  change_app_package_name: ^1.1.0
  banner_carousel: ^1.2.1
  flutter_svg: ^2.0.9
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2
  url_launcher: ^6.2.1
  haversine_distance: ^1.2.1
  permission_handler: ^11.1.0
  location: ^5.0.3
  geocoding: ^2.1.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  rate: ^0.0.2
  google_maps_flutter: ^2.5.0
  firebase_auth: ^4.15.3
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  twitter_login: ^4.4.2
  flutter_facebook_auth: ^6.0.3
  google_sign_in: ^6.2.1
  flutter_polyline_points: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/navbar/active/
    - assets/navbar/unactive/
    - assets/svg/
    - assets/icons/settings/
    - assets/icons/profile/

  fonts:
    - family: font
      fonts:
        - weight: 100
        - asset: assets/fonts/basic.ttf