name: eup
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  change_app_package_name: ^1.1.0
  banner_carousel: ^1.2.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/navbar/active/
    - assets/navbar/unactive/
    - assets/svg/

  fonts:
    - family: font
      fonts:
        - asset: assets/fonts/font.ttf